---
- name: Setup RockyLinux timezone
  hosts: RockyLinux, Ubuntu
  gather_facts: no
  become: true

  tasks:
    - name: Set timezone to Asia/Seoul
      command: timedatectl set-timezone Asia/Seoul

